---
env:
  node: true
  es6: true
plugins:
  -
    typelint
rules:
  eol-last: 0
  no-trailing-spaces: 0
  func-names: 0
  comma-dangle: 0
  no-param-reassign: 0
  no-use-before-define: 0
  global-require: 0
  no-underscore-dangle: 0
  one-var: 0
  one-var-declaration-per-line: 0
  max-len: 0
  valid-typeof: 2
  typelint/typelint: 2
extends: 'airbnb-base/legacy'
settings:
  typelint:
    models:
      json:
        dir: 'models'
        adapters: ['./adapters/to-camel-case']
      redux:
        reducerPath: '/home/roman/frontend/src/client/redux/typelintReducerWrapper.js'
    useCache: false