properties:
  models:
    type: 'object'
    properties:
      json:
        type: 'object'
        proprties:
          dir: 'string'
          swagger: 'string'
          adapters:
            type: 'array'
            items:
              type: 'string'
          exclude:
            type: 'array'
            items:
              type: 'string'
      redux:
        type: 'object'
        properties:
          reducerPath: 'string'
    useCache: 'boolean'

  useCache: 'boolean'